// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TextConverter.proto

package via.sdj3.grpcspringbootx.protobuf;

public interface RequestTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 input_text = 1;</code>
   * @return The inputText.
   */
  int getInputText();
}
